name: diver
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Packages ---
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.1
  firebase_messaging: ^14.9.1
  firebase_database: ^10.5.5
  cloud_functions: ^4.3.0
  
  # --- Location and Maps ---
  geolocator: ^11.1.0
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0

  # --- Background / Notifications ---
  background_fetch: ^1.3.8
  flutter_local_notifications: ^17.1.2

  # --- UI and Animations ---
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.2
  google_fonts: ^6.2.1         #<-- เพิ่มเข้ามา: สำหรับใช้ฟอนต์สวยๆ
  flutter_spinkit: ^5.2.1       #<-- เพิ่มเข้ามา: สำหรับ Loading Animation

  # --- State Management ---
  provider: ^6.1.2              #<-- เพิ่มเข้ามา: สำหรับจัดการสถานะของแอป

  # --- Utility Packages ---
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png          #<-- แก้ไข: ระบุชื่อไฟล์เต็มๆ
  #<-- ตัวอย่าง: การเพิ่มไฟล์อื่นๆ
    # - assets/images/ #<-- การใส่แค่โฟลเดอร์แบบนี้อาจทำให้หาไฟล์ไม่เจอในบางกรณี

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Kanit
  #     fonts:
  #       - asset: assets/fonts/Kanit-Regular.ttf
  #       - asset: assets/fonts/Kanit-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Kanit-Bold.ttf
  #         weight: 700