name: diver
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Packages ---
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.1
  firebase_messaging: ^14.9.1
  firebase_database: ^10.5.5
  cloud_functions: ^4.3.0

  # --- Location and Maps ---
  geolocator: ^11.1.0
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0

  # --- Background / Notifications ---
  background_fetch: ^1.3.8
  flutter_local_notifications: ^17.1.2

  # --- UI and Animations ---
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.2

  # --- Utility Packages ---
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/