name: diver
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.0.2 
  # UI Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.0
  
  # Internationalization
  intl: ^0.19.0

  # --- Firebase Packages ---
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  cloud_functions: ^4.3.0
  firebase_messaging: ^14.9.1
  cloud_firestore: ^4.17.1
  flutter_lints: ^3.0.0

  # --- Location and Maps ---
  geolocator: ^11.1.0
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0


  # --- Background / Notifications ---
  background_fetch: ^1.3.8
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets: ต้องย่อหน้า 2 spaces (อยู่ระดับเดียวกับ uses-material-design)
  assets:
    # - assets/images/ ต้องย่อหน้า 4 spaces (อยู่ข้างใน assets:)
    - assets/images/

