// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8W2GIk0OJUVJUfuX_7KBp86BGkb26z1I',
    appId: '1:914093030372:web:5aa6a93bf07517a448e5f1',
    messagingSenderId: '914093030372',
    projectId: 'shuttle-tracking-7f71a',
    authDomain: 'shuttle-tracking-7f71a.firebaseapp.com',
    databaseURL: 'https://shuttle-tracking-7f71a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-tracking-7f71a.firebasestorage.app',
    measurementId: 'G-36DXLY67WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgX2MNdZTibI6dIG0LQYULoARAesQw9I8',
    appId: '1:914093030372:android:108d4f6ad87151c148e5f1',
    messagingSenderId: '914093030372',
    projectId: 'shuttle-tracking-7f71a',
    databaseURL: 'https://shuttle-tracking-7f71a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-tracking-7f71a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrmQlKu0HKSxpd6qWiXK5M2tJ_uzHIM5w',
    appId: '1:914093030372:ios:11d971a3d12c7c3a48e5f1',
    messagingSenderId: '914093030372',
    projectId: 'shuttle-tracking-7f71a',
    databaseURL: 'https://shuttle-tracking-7f71a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shuttle-tracking-7f71a.firebasestorage.app',
    iosClientId: '914093030372-19jdqvpl0ktghatpjl4rqv1jjorq1unq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
